# Generated by Django 4.2.9 on 2026-01-16 23:33

import collectors.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_tenants.postgresql_backend.base
import secrets
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Collector',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Friendly name for this server', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Optional description')),
                ('api_key', models.CharField(default=secrets.token_urlsafe, help_text='API key for pcc authentication', max_length=64, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Waiting for collector'), ('connected', 'Connected'), ('disconnected', 'Disconnected'), ('error', 'Error')], default='pending', max_length=20)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('hostname', models.CharField(blank=True, max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('os_name', models.CharField(blank=True, help_text='e.g., Ubuntu 22.04', max_length=100)),
                ('os_version', models.CharField(blank=True, max_length=50)),
                ('kernel_version', models.CharField(blank=True, max_length=100)),
                ('vm_brand', models.CharField(choices=[('dell', 'Dell'), ('hp', 'HP'), ('lenovo', 'Lenovo'), ('oracle_cloud', 'Oracle Cloud'), ('azure', 'Azure'), ('aws', 'AWS'), ('gcp', 'Google Cloud'), ('vmware', 'VMware'), ('bare_metal', 'Bare Metal'), ('other', 'Other'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('processor_brand', models.CharField(choices=[('intel', 'Intel'), ('amd', 'AMD'), ('arm', 'ARM'), ('ampere', 'Ampere'), ('other', 'Other'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('processor_model', models.CharField(blank=True, max_length=200)),
                ('vcpus', models.PositiveIntegerField(blank=True, help_text='Number of vCPUs', null=True)),
                ('memory_gib', models.DecimalField(blank=True, decimal_places=2, help_text='Memory in GiB', max_digits=10, null=True)),
                ('storage_gib', models.DecimalField(blank=True, decimal_places=2, help_text='Storage in GiB', max_digits=10, null=True)),
                ('storage_type', models.CharField(choices=[('nvme', 'NVMe SSD'), ('ssd', 'SSD'), ('hdd', 'HDD'), ('block', 'Block Storage'), ('other', 'Other'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collectors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_name', models.CharField(db_index=True, max_length=63, unique=True, validators=[django_tenants.postgresql_backend.base._check_schema_name])),
                ('name', models.CharField(max_length=100)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=253, unique=True)),
                ('is_primary', models.BooleanField(db_index=True, default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='collectors.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CollectedData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('file', models.FileField(upload_to=collectors.models.collected_data_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['csv', 'json', 'txt', 'log', 'gz', 'zip'])])),
                ('file_size', models.PositiveIntegerField(default=0, help_text='File size in bytes')),
                ('row_count', models.PositiveIntegerField(blank=True, help_text='Number of data rows', null=True)),
                ('data_start', models.DateTimeField(blank=True, null=True)),
                ('data_end', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('collector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collected_data', to='collectors.collector')),
            ],
            options={
                'verbose_name_plural': 'Collected data',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Benchmark',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('benchmark_type', models.CharField(default='standard', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('collecting', 'Collecting Data'), ('running', 'Running Analysis'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('cpu_score', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('memory_score', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('disk_score', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('network_score', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('overall_score', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benchmarks', to='collectors.collector')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benchmarks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoadTestResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('units_10pct', models.PositiveIntegerField(default=0, help_text='Work units at 10% CPU')),
                ('units_20pct', models.PositiveIntegerField(default=0, help_text='Work units at 20% CPU')),
                ('units_30pct', models.PositiveIntegerField(default=0, help_text='Work units at 30% CPU')),
                ('units_40pct', models.PositiveIntegerField(default=0, help_text='Work units at 40% CPU')),
                ('units_50pct', models.PositiveIntegerField(default=0, help_text='Work units at 50% CPU')),
                ('units_60pct', models.PositiveIntegerField(default=0, help_text='Work units at 60% CPU')),
                ('units_70pct', models.PositiveIntegerField(default=0, help_text='Work units at 70% CPU')),
                ('units_80pct', models.PositiveIntegerField(default=0, help_text='Work units at 80% CPU')),
                ('units_90pct', models.PositiveIntegerField(default=0, help_text='Work units at 90% CPU')),
                ('units_100pct', models.PositiveIntegerField(default=0, help_text='Work units at 100% CPU')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('benchmark', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loadtest_results', to='collectors.benchmark')),
                ('collector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loadtest_results', to='collectors.collector')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loadtest_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['collector', '-created_at'], name='collectors__collect_8c26b1_idx'), models.Index(fields=['owner', '-created_at'], name='collectors__owner_i_fa1ea8_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='collector',
            index=models.Index(fields=['owner', 'status'], name='collectors__owner_i_69b526_idx'),
        ),
        migrations.AddIndex(
            model_name='collector',
            index=models.Index(fields=['api_key'], name='collectors__api_key_7161d8_idx'),
        ),
        migrations.AddIndex(
            model_name='collector',
            index=models.Index(fields=['created_at'], name='collectors__created_d837c2_idx'),
        ),
        migrations.AddConstraint(
            model_name='collector',
            constraint=models.UniqueConstraint(fields=('owner', 'name'), name='unique_collector_name_per_owner'),
        ),
        migrations.AddIndex(
            model_name='collecteddata',
            index=models.Index(fields=['collector', '-created_at'], name='collectors__collect_d6cd93_idx'),
        ),
        migrations.AddIndex(
            model_name='benchmark',
            index=models.Index(fields=['owner', '-created_at'], name='collectors__owner_i_08b89e_idx'),
        ),
        migrations.AddIndex(
            model_name='benchmark',
            index=models.Index(fields=['collector', '-created_at'], name='collectors__collect_b08d25_idx'),
        ),
        migrations.AddIndex(
            model_name='benchmark',
            index=models.Index(fields=['status'], name='collectors__status_ec81f7_idx'),
        ),
    ]
