# Generated by Django 4.2.9 on 2026-01-17 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collector',
            name='pcd_address',
            field=models.CharField(blank=True, help_text='pcd daemon address (e.g., 192.168.1.100:8080)', max_length=255),
        ),
        migrations.AddField(
            model_name='collector',
            name='pcd_apikey',
            field=models.CharField(blank=True, help_text='API key for pcd daemon authentication', max_length=64),
        ),
    ]
