# Generated by Django 4.2.9 on 2026-01-19 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectors', '0002_add_pcd_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='collector',
            name='hourly_cost',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Hourly cost in USD for price-performance comparison', max_digits=10, null=True),
        ),
    ]
