# Generated by Django 4.2.9 on 2026-01-21 05:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('collectors', '0003_add_hourly_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('cpu_user', models.FloatField(blank=True, null=True)),
                ('cpu_system', models.FloatField(blank=True, null=True)),
                ('cpu_iowait', models.FloatField(blank=True, null=True)),
                ('cpu_idle', models.FloatField(blank=True, null=True)),
                ('cpu_steal', models.FloatField(blank=True, null=True)),
                ('mem_total', models.FloatField(blank=True, null=True)),
                ('mem_used', models.FloatField(blank=True, null=True)),
                ('mem_available', models.FloatField(blank=True, null=True)),
                ('mem_buffers', models.FloatField(blank=True, null=True)),
                ('mem_cached', models.FloatField(blank=True, null=True)),
                ('disk_read_bytes', models.BigIntegerField(blank=True, null=True)),
                ('disk_write_bytes', models.BigIntegerField(blank=True, null=True)),
                ('disk_read_ops', models.BigIntegerField(blank=True, null=True)),
                ('disk_write_ops', models.BigIntegerField(blank=True, null=True)),
                ('net_rx_bytes', models.BigIntegerField(blank=True, null=True)),
                ('net_tx_bytes', models.BigIntegerField(blank=True, null=True)),
                ('net_rx_packets', models.BigIntegerField(blank=True, null=True)),
                ('net_tx_packets', models.BigIntegerField(blank=True, null=True)),
                ('collector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='collectors.collector')),
            ],
            options={
                'verbose_name': 'Performance Metric',
                'verbose_name_plural': 'Performance Metrics',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['collector', '-timestamp'], name='collectors__collect_9e5925_idx'), models.Index(fields=['collector', 'timestamp'], name='collectors__collect_fb123f_idx'), models.Index(fields=['-timestamp'], name='collectors__timesta_579c75_idx')],
                'unique_together': {('collector', 'timestamp')},
            },
        ),
    ]
