# Generated by Django 4.2.9 on 2026-01-21 16:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('collectors', '0004_add_performance_metric'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrickleSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('saved', 'Saved')], default='active', max_length=20)),
                ('name', models.CharField(blank=True, help_text='Optional name for this collection session', max_length=200)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('last_data_at', models.DateTimeField(blank=True, null=True)),
                ('sample_count', models.PositiveIntegerField(default=0)),
                ('frequency_seconds', models.PositiveIntegerField(blank=True, help_text='Detected sampling frequency in seconds', null=True)),
                ('saved_file', models.CharField(blank=True, help_text="Path to saved CSV file when status is 'saved'", max_length=500)),
                ('collector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trickle_sessions', to='collectors.collector')),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['collector', '-started_at'], name='collectors__collect_befeb8_idx'), models.Index(fields=['status'], name='collectors__status_daa491_idx'), models.Index(fields=['collector', 'status'], name='collectors__collect_4aca11_idx'), models.Index(fields=['-started_at'], name='collectors__started_aebc43_idx')],
            },
        ),
    ]
