# Generated by Django 4.2.9 on 2026-02-23 17:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('collectors', '0005_add_trickle_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlobTarget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Friendly name for this blob target', max_length=100)),
                ('account_name', models.CharField(help_text='Azure Storage account name', max_length=100)),
                ('container_name', models.CharField(help_text='Blob container name', max_length=63)),
                ('auth_method', models.CharField(choices=[('key_vault', 'Azure Key Vault'), ('sas_token', 'SAS Token'), ('connection_string', 'Connection String')], default='connection_string', max_length=20)),
                ('key_vault_secret_name', models.CharField(blank=True, help_text='Key Vault secret name containing the connection string', max_length=200)),
                ('sas_token', models.TextField(blank=True, help_text='SAS token for container-level access')),
                ('connection_string', models.TextField(blank=True, help_text='Azure Storage connection string')),
                ('path_prefix', models.CharField(blank=True, help_text='Optional path prefix within the container', max_length=200)),
                ('export_format', models.CharField(choices=[('csv', 'CSV'), ('json', 'JSON')], default='csv', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('last_tested_at', models.DateTimeField(blank=True, null=True)),
                ('last_test_success', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blob_targets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BlobExport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('blob_path', models.CharField(blank=True, max_length=500)),
                ('blob_url', models.URLField(blank=True, max_length=1000)),
                ('records_exported', models.PositiveIntegerField(default=0)),
                ('file_size_bytes', models.PositiveIntegerField(default=0)),
                ('export_format', models.CharField(default='csv', max_length=10)),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blob_target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exports', to='collectors.blobtarget')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blob_exports', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blob_exports', to='collectors.tricklesession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='blobtarget',
            constraint=models.UniqueConstraint(fields=('owner', 'name'), name='unique_blob_target_name_per_owner'),
        ),
        migrations.AddIndex(
            model_name='blobexport',
            index=models.Index(fields=['session', '-created_at'], name='collectors__session_c4575a_idx'),
        ),
        migrations.AddIndex(
            model_name='blobexport',
            index=models.Index(fields=['owner', '-created_at'], name='collectors__owner_i_3e5ce9_idx'),
        ),
        migrations.AddIndex(
            model_name='blobexport',
            index=models.Index(fields=['status'], name='collectors__status_1e09a9_idx'),
        ),
    ]
