# Generated by Django 4.2.9 on 2026-02-23 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectors', '0006_blobtarget_blobexport_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='performancemetric',
            name='disk_read_iops',
            field=models.FloatField(blank=True, help_text='Read IOPS (ops/sec)', null=True),
        ),
        migrations.AddField(
            model_name='performancemetric',
            name='disk_read_mbps',
            field=models.FloatField(blank=True, help_text='Read throughput (MB/sec)', null=True),
        ),
        migrations.AddField(
            model_name='performancemetric',
            name='disk_write_iops',
            field=models.FloatField(blank=True, help_text='Write IOPS (ops/sec)', null=True),
        ),
        migrations.AddField(
            model_name='performancemetric',
            name='disk_write_mbps',
            field=models.FloatField(blank=True, help_text='Write throughput (MB/sec)', null=True),
        ),
        migrations.AddField(
            model_name='performancemetric',
            name='net_rx_mbps',
            field=models.FloatField(blank=True, help_text='Receive rate (Mbit/sec)', null=True),
        ),
        migrations.AddField(
            model_name='performancemetric',
            name='net_rx_pps',
            field=models.FloatField(blank=True, help_text='Receive packets/sec', null=True),
        ),
        migrations.AddField(
            model_name='performancemetric',
            name='net_tx_mbps',
            field=models.FloatField(blank=True, help_text='Transmit rate (Mbit/sec)', null=True),
        ),
        migrations.AddField(
            model_name='performancemetric',
            name='net_tx_pps',
            field=models.FloatField(blank=True, help_text='Transmit packets/sec', null=True),
        ),
        migrations.AddField(
            model_name='tricklesession',
            name='previous_sample',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
